In [68]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm
%matplotlib notebook
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [98]:
f=np.array([0.5,0,-0.5])
b=np.array([0.9,1.1,1])
r=np.array([-0.05,0.15,0])

B=np.vstack([np.ones(3),b]).T
B

S=np.diag(np.ones(3)*0.2)
Sinv=np.diag(np.ones(3)*5)

array([[1. , 0.9],
       [1. , 1.1],
       [1. , 1. ]])

In [87]:
IC=np.corrcoef(f,r)
IC

array([[ 1.        , -0.24019223],
       [-0.24019223,  1.        ]])

Lagrange multipliers

In [99]:
l=np.linalg.inv(B.T.dot(Sinv).dot(B)).dot(B.T.dot(Sinv).dot(f))
l

array([ 2.5, -2.5])

Risk-adjusted Factors

In [89]:
F=(f-l.dot(B.T))/np.diag(S)
F

array([ 1.25,  1.25, -2.5 ])

Returns of the risk factors

In [100]:
m=np.linalg.inv(B.T.dot(Sinv).dot(B)).dot(B.T.dot(Sinv).dot(r))
m

array([-0.96666667,  1.        ])

Risk-adjusted Returns

In [92]:
R=(r-m.dot(B.T))/np.diag(S)
R
R.mean()

array([ 0.08333333,  0.08333333, -0.16666667])

2.0354088784794536e-16

In [93]:
IC_risk_adjusted=np.corrcoef(R,F)
IC_risk_adjusted

array([[1., 1.],
       [1., 1.]])

Note that to get the return of risk factors, you can regress stock returns on the loadings matrix. The coefficients of the regression are the returns of risk factors with const=m0 that will make avg(R)=0

In [94]:
results = sm.OLS(r, B).fit()

In [95]:
results.summary()

/home/alex/anaconda3/lib/python3.6/site-packages/statsmodels/stats/stattools.py:72: ValueWarning: omni_normtest is not valid with less than 8 observations; 3 samples were given.
  "samples were given." % int(n), ValueWarning)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.923
Model:                            OLS   Adj. R-squared:                  0.846
Method:                 Least Squares   F-statistic:                     12.00
Date:                Sat, 13 Apr 2019   Prob (F-statistic):              0.179
Time:                        19:57:26   Log-Likelihood:                 6.9865
No. Observations:                   3   AIC:                            -9.973
Df Residuals:                       1   BIC:                            -11.78
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.9667      0.290     -3.338      0.185      -4.647       2.714
x1             1.0000      0.289      3.464      0.179      -2.668       4.668
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.500
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.531
Skew:                          -0.707   Prob(JB):                        0.767
Kurtosis:                       1.500   Cond. No.                         24.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [97]:
np.isclose(results.params,m)

array([ True,  True])